package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.input.MouseEvent;

public class SampleController {
	@FXML
	private ComboBox<String> idioma;
	@FXML
	private TextField color;
	@FXML
	private Button btnCercar;
	@FXML
	private Label colorCaste;
	@FXML
	private Label colorFran;

	// Event Listener on ComboBox[#idioma].onMouseClicked
	@FXML
	public void triarColor(MouseEvent event) {
		
		idioma.getItems().addAll(
				"Català",
				"Castellà",
				"Francès",
				"Anglès"
				);
	}
	// Event Listener on Button[#btnCercar].onMouseClicked
	@FXML
	public void traduirColor(MouseEvent event) {
		// TODO Autogenerated
	}
}
